### PR TITLE
Create Kth smallest element in BST

### PR DESCRIPTION
**Pull request by Adityap-3055**

### CODE REVIEW

**Comment by Adityap-3055** [comment]
Providing java pattern solution

**Comment by Almas-Ali** [comment]
Please follow our rules to get a successful merge. Follow me and add star in this repository.

**Comment by Adityap-3055** [comment]
updated file 
added my github name to the file
star this repo and followed you

**Comment by Adityap-3055** [comment]
@Almas-Ali please review the changes and merge it

**Pull request merged**
