### PR TITLE
Added 2nd Method 

### PR DESCRIPTION
**Pull request by Rohit-kumar-yadav**

### CODE REVIEW

**Comment by Almas-Ali** [comment]
@Rohit-kumar-yadav Follow me on Github.

**Comment by Almas-Ali** [comment]
@Rohit-kumar-yadav Follow me on Github.

**Comment by Rohit-kumar-yadav** [comment]
Can you tell me more about why invalid

**Comment by Almas-Ali** [comment]
@Rohit-kumar-yadav Just follow me on Github to get it merge.

**Comment by Rohit-kumar-yadav** [comment]
Done check it

**Pull request merged**
