### PR TITLE
Added jospehus problem

### PR DESCRIPTION
**Pull request by pankajsirari222**
It is one of the important problems which uses  recursion.

### CODE REVIEW

**Comment by Almas-Ali** [comment]
Please follow our rules to get a successful merge. Follow me and add star in this repository.

**Comment by pankajsirari222** [comment]
@Almas-Ali Please check now, I added the question

**Comment by pankajsirari222** [comment]
@Almas-Ali  Also, following you and Starred the repo.

**Comment by pankajsirari222** [comment]
@Almas-Ali Kindly check my PR

**Pull request merged**
